# Generated by Django 5.0.6 on 2024-07-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acessorio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acessorio",
            old_name="nome",
            new_name="acessorio",
        ),
        migrations.RenameField(
            model_name="acessorio",
            old_name="site",
            new_name="descrição",
        ),
    ]
