# Generated by Django 5.0.6 on 2024-07-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_nome_acessorio_acessorio_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="acessorio",
            old_name="acessorio",
            new_name="descricao",
        ),
        migrations.RemoveField(
            model_name="acessorio",
            name="descrição",
        ),
    ]
